# Generated by Django 6.0.7 on 2026-07-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_transaction_source_document_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDocumentNumberClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_number', models.CharField(max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('RECEIVING', 'Penerimaan'), ('OPENING_BALANCE', 'Saldo Awal')], max_length=30)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'source_document_number_claims',
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='idx_source_doc_claim_source')],
            },
        ),
    ]
