# Generated by Django 6.0.7 on 2026-08-19 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_item_barcode'),
        ('receiving', '0020_receiving_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivingitem',
            name='posted_source_document_number',
            field=models.CharField(blank=True, help_text='Actual stock source document layer posted for this item.', max_length=100),
        ),
        migrations.AddField(
            model_name='receivingitem',
            name='posted_sumber_dana',
            field=models.ForeignKey(blank=True, help_text='Actual funding source layer posted to stock for this item.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_receiving_items', to='items.fundingsource'),
        ),
    ]
