# Generated by Django 6.0.8 on 2026-08-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_opname', '0009_merge_stock_opname_legacy_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockopnameitem',
            name='completion_stock_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Frozen stock quantity when the opname was completed', max_digits=12, null=True),
        ),
    ]
